#pragma once

namespace graphics
{
enum class shader_property_type
{
    spt_float,
    spt_vec2,
    spt_vec3,
    spt_vec4,
    spt_double,
    spt_dvec2,
    spt_dvec3,
    spt_dvec4,
    spt_int,
    spt_ivec2,
    spt_ivec3,
    spt_ivec4,
    spt_unsigned_int,
    spt_uvec2,
    spt_uvec3,
    spt_uvec4,
    spt_bool,
    spt_bvec2,
    spt_bvec3,
    spt_bvec4,
    spt_mat2,
    spt_mat3,
    spt_mat4,
    spt_mat2x3,
    spt_mat2x4,
    spt_mat3x2,
    spt_mat3x4,
    spt_mat4x2,
    spt_mat4x3,
    spt_dmat2,
    spt_dmat3,
    spt_dmat4,
    spt_dmat2x3,
    spt_dmat2x4,
    spt_dmat3x2,
    spt_dmat3x4,
    spt_dmat4x2,
    spt_dmat4x3,
    spt_sampler1D,
    spt_sampler2D,
    spt_sampler3D,
    spt_samplerCube,
    spt_sampler1DShadow,
    spt_sampler2DShadow,
    spt_sampler1DArray,
    spt_sampler2DArray,
    spt_sampler1DArrayShadow,
    spt_sampler2DArrayShadow,
    spt_sampler2DMS,
    spt_sampler2DMSArray,
    spt_samplerCubeShadow,
    spt_samplerBuffer,
    spt_sampler2DRect,
    spt_sampler2DRectShadow,
    spt_isampler1D,
    spt_isampler2D,
    spt_isampler3D,
    spt_isamplerCube,
    spt_isampler1DArray,
    spt_isampler2DArray,
    spt_isampler2DMS,
    spt_isampler2DMSArray,
    spt_isamplerBuffer,
    spt_isampler2DRect,
    spt_usampler1D,
    spt_usampler2D,
    spt_usampler3D,
    spt_usamplerCube,
    spt_usampler1DArray,
    spt_usampler2DArray,
    spt_usampler2DMS,
    spt_usampler2DMSArray,
    spt_usamplerBuffer,
    spt_usampler2DRect,
    spt_image1D,
    spt_image2D,
    spt_image3D,
    spt_image2DRect,
    spt_imageCube,
    spt_imageBuffer,
    spt_image1DArray,
    spt_image2DArray,
    spt_image2DMS,
    spt_image2DMSArray,
    spt_iimage1D,
    spt_iimage2D,
    spt_iimage3D,
    spt_iimage2DRect,
    spt_iimageCube,
    spt_iimageBuffer,
    spt_iimage1DArray,
    spt_iimage2DArray,
    spt_iimage2DMS,
    spt_iimage2DMSArray,
    spt_uimage1D,
    spt_uimage2D,
    spt_uimage3D,
    spt_uimage2DRect,
    spt_uimageCube,
    spt_uimageBuffer,
    spt_uimage1DArray,
    spt_uimage2DArray,
    spt_uimage2DMS,
    spt_uimage2DMSArray,
    spt_atomic_uint,
};

struct shader_property
{
    std::string name;
    int location_info;
    int size;
    std::any value;
    shader_property_type type;
};
} // namespace graphics
